apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
  namespace: monitoring
  name: test-alert-rule
spec:
  groups:
  - name: omnia-prevent.alerts
    rules:
    # - alert: kv_issue
    #   expr: |
    #     count(kube_pod_status_phase{phase="Running",namespace="kv"}) < 7
    #   for: 1m
    #   labels:
    #     namespace: monitoring
    #     severity: warning
    #   annotations:
    #     description: Test alert {{ $labels.pod }}
      - alert: container
        expr: |
          count(kube_pod_status_phase{phase="Running",namespace="syer"}) > 4
        for: 1m
        labels:
          namespace: monitoring
          severity: warning
          job: service-kv
        annotations:
          description: one container in a {{ $labels.pod }} is down       
